"""VerseCompat: HuggingFace / PyTorch compatibility adapters (optional, used only when installed).

提供：
- ``load_hf_state_dict``: 从 HuggingFace repo 或本地路径加载权重到 verse_torch.Tensor
- ``torch_api``: PyTorch 兼容的别名（``Tensor``, ``nn``, ``optim``, 工厂函数等）
"""

from .hf_loader import load_hf_state_dict
from .torch_api import (
    Tensor,
    nn,
    optim,
    losses,
    Linear,
    Embedding,
    LayerNorm,
    RMSNorm,
    Dropout,
    Module,
    Sequential,
    ModuleList,
    SGD,
    Adam,
    AdamW,
    cross_entropy,
    mse_loss,
    no_grad,
    enable_grad,
    set_grad_enabled,
    is_grad_enabled,
    tensor,
    zeros,
    ones,
    randn,
    rand,
    arange,
    full,
    empty,
    eye,
    softmax,
    sigmoid,
    relu,
    gelu,
    tanh,
    exp,
    log,
    sqrt,
    matmul,
    cat,
    stack,
    float16,
    float32,
    float64,
    bfloat16,
    int8,
    int16,
    int32,
    int64,
    uint8,
)

__version__ = "0.1.0"

__all__ = [
    "load_hf_state_dict",
    # torch_api
    "Tensor",
    "nn",
    "optim",
    "losses",
    "Linear",
    "Embedding",
    "LayerNorm",
    "RMSNorm",
    "Dropout",
    "Module",
    "Sequential",
    "ModuleList",
    "SGD",
    "Adam",
    "AdamW",
    "cross_entropy",
    "mse_loss",
    "no_grad",
    "enable_grad",
    "set_grad_enabled",
    "is_grad_enabled",
    "tensor",
    "zeros",
    "ones",
    "randn",
    "rand",
    "arange",
    "full",
    "empty",
    "eye",
    "softmax",
    "sigmoid",
    "relu",
    "gelu",
    "tanh",
    "exp",
    "log",
    "sqrt",
    "matmul",
    "cat",
    "stack",
    "float16",
    "float32",
    "float64",
    "bfloat16",
    "int8",
    "int16",
    "int32",
    "int64",
    "uint8",
]
